version: 2
formats: [htmlzip]
sphinx:
   configuration: docs/source/conf.py
python:
   install:
     - method: pip
       path: .
       extra_requirements:
         - dev
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.11"