coverage:
  ignore:
    - "tests/"
    - "**/test_*.py"
  status:
    patch:
      default:
        informational: false
        target: 85%     # New code should have % coverage
        threshold: 5%   # Allow up to % below the target before failing
    project:
      default:
        informational: false
        target: 45%           # Fail if overall coverage drops below
        threshold: 2%         # Allow 2% decrease from previous coverage